<?php

namespace ByJG\Mail;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-04 at 13:08:23.
 */
class EnvelopeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Envelope
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Envelope;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ByJG\Mail\Envelope::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ByJG\Mail\Envelope::getFrom
     * @covers ByJG\Mail\Envelope::setFrom
     */
    public function testGetFrom()
    {
        $this->object->setFrom('some@email.com');
        $this->assertEquals('some@email.com', $this->object->getFrom());

        $this->object->setFrom('some@email.com', 'John Doe');
        $this->assertEquals('"John Doe" <some@email.com>', $this->object->getFrom());
    }

    /**
     * @covers ByJG\Mail\Envelope::getTo
     * @covers ByJG\Mail\Envelope::addTo
     */
    public function testGetTo()
    {
        $this->object->addTo('some@email.com');
        $this->assertEquals(['some@email.com'], $this->object->getTo());

        $this->object->addTo('some@email.com', 'John Doe');
        $this->assertEquals(['some@email.com', '"John Doe" <some@email.com>'], $this->object->getTo());
    }

    /**
     * @covers ByJG\Mail\Envelope::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ByJG\Mail\Envelope::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ByJG\Mail\Envelope::getCC
     * @covers ByJG\Mail\Envelope::addCC
     */
    public function testGetCC()
    {
        $this->object->addCC('some@email.com');
        $this->assertEquals(['some@email.com'], $this->object->getCC());

        $this->object->addCC('some@email.com', 'John Doe');
        $this->assertEquals(['some@email.com', '"John Doe" <some@email.com>'], $this->object->getCC());
    }

    /**
     * @covers ByJG\Mail\Envelope::getBCC
     * @covers ByJG\Mail\Envelope::addBCC
     */
    public function testGetBCC()
    {
        $this->object->addBCC('some@email.com');
        $this->assertEquals(['some@email.com'], $this->object->getBCC());

        $this->object->addBCC('some@email.com', 'John Doe');
        $this->assertEquals(['some@email.com', '"John Doe" <some@email.com>'], $this->object->getBCC());
    }


    /**
     * @covers ByJG\Mail\Envelope::getBody
     * @covers ByJG\Mail\Envelope::setBody
     * @covers ByJG\Mail\Envelope::getBodyText
     */
    public function testGetBody()
    {
        $this->object->setBody('<p><b>Some title</b></p><p>Other test<br/>Break</p>');
        $this->assertEquals('<p><b>Some title</b></p><p>Other test<br/>Break</p>', $this->object->getBody());
        $this->assertEquals("Some title\nOther test\nBreak\n", $this->object->getBodyText());
    }


    /**
     * @covers ByJG\Mail\Envelope::getAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
